// ─── Brand colors ─────────────────────────────────────────────────────────────
export const C = {
  dark:    '#06080f',
  dark2:   '#0a0d18',
  surface: '#0e1422',
  panel:   '#131928',
  blue:    '#2a8fc4',
  cyan:    '#00c8ff',
  cyanDim: 'rgba(0,200,255,0.12)',
  border:  'rgba(42,143,196,0.18)',
  borderB: 'rgba(0,200,255,0.28)',
  text:    '#e8edf5',
  dim:     '#8899aa',
  dim2:    '#3a4556',
}

// ─── Services ─────────────────────────────────────────────────────────────────
export const SERVICES = [
  {
    slug: 'interior',
    title: 'Interior Detailing',
    tagline: 'Deep clean from dash to cargo',
    price: '$150 – $200',
    img: 'https://images.unsplash.com/photo-1620584899131-a5ff5f8fbb03?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1620584899131-a5ff5f8fbb03?w=1400&h=700&fit=crop&auto=format',
    icon: '🪑',
    desc: 'Our interior detail leaves every surface spotless. We vacuum every crevice, steam-clean hard surfaces, shampoo carpets and seats, clean vents, wipe all panels, and eliminate odors at the source.',
    includes: [
      'Full vacuum — carpets, seats, trunk, headliner',
      'Steam cleaning of all hard surfaces & vents',
      'Carpet & upholstery shampoo extraction',
      'Dashboard, door panels & console wipe-down',
      'Window & mirror cleaning inside',
      'Leather conditioning (if applicable)',
      'Odor neutralization treatment',
      'Final inspection & air freshener',
    ],
    duration: '2–4 hrs',
    vehicles: 'Sedan, SUV, Truck, Van',
  },
  {
    slug: 'exterior',
    title: 'Exterior Detailing',
    tagline: 'Showroom shine, start to finish',
    price: '$150 – $200',
    img: 'https://images.unsplash.com/photo-1708805282706-f44730b7e527?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1708805282706-f44730b7e527?w=1400&h=700&fit=crop&auto=format',
    icon: '✨',
    desc: 'A complete exterior refresh using professional foam wash, iron decontamination, clay bar treatment, and a hand-applied protective sealant to make the paint pop and stay protected.',
    includes: [
      'Pre-rinse & foam cannon application',
      'Iron & fallout decontamination spray',
      'Clay bar treatment for paint smoothness',
      'Hand wash & two-bucket method',
      'Wheel, tire & brake dust removal',
      'Wheel well cleaning',
      'Exterior trim dressing & restoration',
      'Window & glass cleaning outside',
      'Hand-applied paint sealant',
    ],
    duration: '2–3 hrs',
    vehicles: 'Sedan, SUV, Truck, Van',
  },
  {
    slug: 'full-service',
    title: 'Full Service Package',
    tagline: 'Complete inside & out transformation',
    price: '$229',
    originalPrice: '$300',
    img: 'https://images.unsplash.com/photo-1708805282676-0c15476eb8a2?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1708805282676-0c15476eb8a2?w=1400&h=700&fit=crop&auto=format',
    icon: '⭐',
    desc: 'Everything in our Interior + Exterior packages combined into one complete session. Best value for a total transformation inside and out — like driving a new car.',
    includes: [
      'Everything in Interior Detailing',
      'Everything in Exterior Detailing',
      'Interior & exterior glass polishing',
      'Engine bay wipe-down (on request)',
      'Final quality inspection',
      'Courtesy air freshener',
    ],
    duration: '4–6 hrs',
    vehicles: 'Sedan, SUV, Truck, Van',
    featured: true,
  },
  {
    slug: 'paint-correction',
    title: 'Paint Correction',
    tagline: 'Erase swirls, scratches & oxidation',
    price: 'From $335',
    img: 'https://images.unsplash.com/photo-1622329821376-a19fd6002562?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1622329821376-a19fd6002562?w=1400&h=700&fit=crop&auto=format',
    icon: '🔬',
    desc: 'Multi-stage machine polishing that removes swirl marks, light scratches, water spots, and oxidation — restoring deep, mirror-like clarity to your paint.',
    includes: [
      'Full decontamination wash',
      'Clay bar & iron remover',
      'Paint thickness measurement',
      'Single or multi-stage machine polish',
      'Swirl mark & scratch removal',
      'Water spot & oxidation elimination',
      'IPA wipe-down to inspect work',
      'Paint protection sealant applied',
    ],
    duration: '4–8 hrs',
    vehicles: 'All vehicles — pricing varies by size',
  },
  {
    slug: 'ceramic-coating',
    title: 'Ceramic Coating',
    tagline: 'Years of protection in one application',
    price: 'From $500',
    img: 'https://images.unsplash.com/photo-1528597469186-bddab681a37f?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1528597469186-bddab681a37f?w=1400&h=700&fit=crop&auto=format',
    icon: '💎',
    desc: 'Professional-grade nano-ceramic protection that bonds to your paint at the molecular level. Repels UV, water, road grime, and minor scratches for years.',
    includes: [
      'Full paint decontamination & prep',
      'Single-stage paint correction included',
      'IPA panel wipe prep',
      'Professional ceramic coating application',
      'Cure time management',
      'Hydrophobic water-beading layer',
      'UV & oxidation protection',
      'Multi-year durability',
    ],
    duration: '1–2 days',
    vehicles: 'All vehicles — pricing varies by size',
  },
  {
    slug: 'headlight-restoration',
    title: 'Headlight Restoration',
    tagline: 'See clearly. Stay safe.',
    price: '$75 / Both $150',
    img: 'https://images.unsplash.com/photo-1708805283017-c662be2c7a44?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1708805283017-c662be2c7a44?w=1400&h=700&fit=crop&auto=format',
    icon: '💡',
    desc: 'Multi-step wet sanding and UV-resistant sealing removes haze, yellowing, and cloudiness from headlight lenses — restoring full clarity and improving nighttime visibility.',
    includes: [
      'Wet sanding with multiple grits',
      'Compound polishing',
      'UV-resistant clear coat sealant',
      'Before & after comparison',
    ],
    duration: '1–2 hrs',
    vehicles: 'All vehicles',
  },
  {
    slug: 'mold-remediation',
    title: 'Mold Remediation',
    tagline: 'Eliminate mold at the source',
    price: 'Call for Quote',
    img: 'https://images.unsplash.com/photo-1620584898989-d39f7f9ed1b7?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1620584898989-d39f7f9ed1b7?w=1400&h=700&fit=crop&auto=format',
    icon: '🛡️',
    desc: 'Professional mold removal using steam treatment, high-powered water extraction, and ozone therapy. We treat the root cause, not just the surface — backed by a 6-month mold-free warranty.',
    includes: [
      'Full interior inspection & assessment',
      'High-temp steam mold treatment',
      'Water extraction & drying',
      'Ozone treatment to kill spores',
      'Anti-microbial application',
      'Final air quality check',
      '6-month mold-free warranty',
    ],
    duration: 'Half to full day',
    vehicles: 'All vehicles — severity-based pricing',
    warranty: true,
  },
  {
    slug: 'rv-detailing',
    title: 'RV / Motorhome Detailing',
    tagline: 'Premium care for your home on wheels',
    price: 'Call for Quote',
    img: 'https://images.unsplash.com/photo-1708805282695-ef186db20192?w=700&h=480&fit=crop&auto=format',
    heroImg: 'https://images.unsplash.com/photo-1708805282695-ef186db20192?w=1400&h=700&fit=crop&auto=format',
    icon: '🚌',
    desc: 'Specialized detailing for RVs and motorhomes — exterior wash, roof cleaning, oxidation removal, and ceramic coating options to protect your investment.',
    includes: [
      'Full exterior wash & rinse',
      'Roof & awning cleaning',
      'Oxidation removal & polish',
      'Rubber seal conditioning',
      'Ceramic coating available',
      'Interior detailing available',
    ],
    duration: 'Varies by size',
    vehicles: 'Class A, B, C motorhomes & travel trailers',
  },
]

// ─── Testimonials (styled as Google reviews) ─────────────────────────────────
export const TESTIMONIALS = [
  {
    name: 'Jake M.',
    initials: 'JM',
    avatarColor: '#4285F4',
    stars: 5,
    text: 'Amazing work! My car looks brand new. Super professional and convenient. They came right to my driveway — couldn\'t be easier. Will definitely book again.',
    service: 'Full Service Package',
    timeAgo: '2 weeks ago',
  },
  {
    name: 'Sarah L.',
    initials: 'SL',
    avatarColor: '#34A853',
    stars: 5,
    text: 'Best detailing service in Everett! Highly recommend Everett Lux Detailing. The ceramic coating looks incredible and has held up perfectly through the rain.',
    service: 'Ceramic Coating',
    timeAgo: '1 month ago',
  },
  {
    name: 'Mike R.',
    initials: 'MR',
    avatarColor: '#EA4335',
    stars: 5,
    text: 'They brought my truck back to life. Great attention to detail — the paint correction removed scratches I thought were permanent. Worth every penny.',
    service: 'Paint Correction',
    timeAgo: '1 month ago',
  },
  {
    name: 'Tanya K.',
    initials: 'TK',
    avatarColor: '#FBBC05',
    stars: 5,
    text: 'I had mold in my car from a leak and they eliminated it completely. The 6-month warranty gave me total peace of mind. Fantastic team, great communication throughout.',
    service: 'Mold Remediation',
    timeAgo: '2 months ago',
  },
  {
    name: 'Derek P.',
    initials: 'DP',
    avatarColor: '#4285F4',
    stars: 5,
    text: 'Used them for my RV before a big trip — the exterior looks showroom-fresh. Vlad and the team were professional, on time, and incredibly thorough.',
    service: 'RV Detailing',
    timeAgo: '2 months ago',
  },
  {
    name: 'Amanda W.',
    initials: 'AW',
    avatarColor: '#34A853',
    stars: 5,
    text: 'My headlights were so foggy I was nervous driving at night. After restoration they look brand new. Quick, affordable, and effective — exactly what I needed.',
    service: 'Headlight Restoration',
    timeAgo: '3 months ago',
  },
]

// ─── Service area cities ──────────────────────────────────────────────────────
export const SERVICE_AREAS = [
  { city: 'Everett', slug: 'everett', note: 'Home Base', img: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&h=300&fit=crop&auto=format' },
  { city: 'Marysville', slug: 'marysville', note: 'North Snohomish', img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=300&fit=crop&auto=format' },
  { city: 'Lynnwood', slug: 'lynnwood', note: 'South Snohomish', img: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop&auto=format' },
  { city: 'Mukilteo', slug: 'mukilteo', note: 'Waterfront', img: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&h=300&fit=crop&auto=format' },
  { city: 'Edmonds', slug: 'edmonds', note: 'South Snohomish', img: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=400&h=300&fit=crop&auto=format' },
  { city: 'Mill Creek', slug: 'mill-creek', note: 'Snohomish County', img: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=400&h=300&fit=crop&auto=format' },
  { city: 'Bothell', slug: 'bothell', note: 'King / Snohomish', img: 'https://images.unsplash.com/photo-1444084316824-dc26d6657664?w=400&h=300&fit=crop&auto=format' },
  { city: 'Kirkland', slug: 'kirkland', note: 'Eastside', img: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=400&h=300&fit=crop&auto=format' },
  { city: 'Bellevue', slug: 'bellevue', note: 'Eastside', img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&auto=format' },
  { city: 'Seattle', slug: 'seattle', note: 'King County', img: 'https://images.unsplash.com/photo-1438401171849-74ac270044ee?w=400&h=300&fit=crop&auto=format' },
  { city: 'Redmond', slug: 'redmond', note: 'Eastside', img: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop&auto=format' },
  { city: 'Shoreline', slug: 'shoreline', note: 'North Seattle', img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=300&fit=crop&auto=format' },
]

// ─── Car brand marquee ────────────────────────────────────────────────────────
export const BRANDS = ['BMW','Mercedes-Benz','Audi','Porsche','Tesla','Toyota','Ford','Chevrolet','Dodge','Honda','Lexus','Cadillac','Range Rover','Jeep','Ram','Subaru','Volkswagen','Kia']

// ─── Stats ────────────────────────────────────────────────────────────────────
export const STATS = [
  { num: 500, suffix: '+', label: 'Cars Detailed' },
  { num: 5, suffix: '★', label: 'Google Rating' },
  { num: 6, suffix: '-Mo', label: 'Mold Warranty' },
  { num: 100, suffix: '%', label: 'Mobile Service' },
]

// ─── Team ─────────────────────────────────────────────────────────────────────
export const TEAM = [
  { name: 'Vlad', role: 'Owner & Project Manager', bio: 'Founded Everett Lux Detailing with a passion for perfection. Vlad oversees every job and ensures the highest standard of quality on each vehicle.' },
  { name: 'Artom', role: 'Lead Detailer', bio: 'Artom brings precision and expertise to every detail. Specializing in paint correction and ceramic coatings, he treats each car like his own.' },
  { name: 'Max', role: 'Detailer', bio: 'Max is meticulous and thorough, delivering exceptional interior and exterior results on every job — big or small.' },
]
